title: "Kyoungrae's AI Study"
description: "Machine Learning, Deep Learning, AI Study Blog"
remote_theme: "minimal-mistakes/jekyll-theme"  # Gaussian37처럼 깔끔한 테마 적용
baseurl: ""  
url: "https://Kyoungrae-Noh.github.io"

# 네비게이션 설정
navbar-links:
  Machine Learning:
    - "Bias vs Variance": "/questions/bias_vs_variance"
    - "Overfitting vs Underfitting": "/questions/underfitting_overfitting"
    - "Gradient Descent": "/questions/Gradient_Descent"

# 마크다운 및 플러그인
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# SEO 및 기본 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
