title: "Kyoungrae Noh Blog"
author: "Kyoungrae Noh"
email: "your.email@example.com"
description: "Computer Vision, AI, ML, Deep Learning Blog"
baseurl: ""
url: "https://kyoungrae-noh.github.io"
github_username: "Kyoungrae-Noh"

theme: minima  # or 사용할 테마 설정

# 네비게이션 바 설정
navbar-links:
  ALL: "/"
  ML: "/ml"
  DL: "/dl"
  Vision: "/vision"
  Math: "/math"
  Python: "/python"
  ETC: "/etc"

# 포스트 설정
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# 플러그인 (필요시)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# 기본 페이지네이션
paginate: 5
paginate_path: "/page:num/"

# 마크다운 변환 설정
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
