title: "Kyoungrae's Study Page"
description: "A collection of AI, ML, and DL interview questions and concepts"
theme: minima  # 기본 제공 테마 (필요에 따라 변경 가능)
baseurl: ""  
url: "https://Kyoungrae-Noh.github.io"

# 마크다운 및 URL 설정
markdown: kramdown
permalink: pretty

# 네비게이션 바 설정
navbar-links:
  Home: "/index.html"
  ML:
    "Gradient Descent": "/questions/Gradient_Descent.html"
    "Bias vs Variance": "/questions/Bias_vs_Variance.html"
    "Overfitting vs Underfitting": "/questions/Overfitting_vs_Underfitting.html"
  DL:
    "CNN": "/questions/CNN.html"
    "RNN": "/questions/RNN.html"
  Math:
    "Linear Algebra": "/questions/Linear_Algebra.html"
    "Probability": "/questions/Probability.html"
  About: "/about.html"

# Plugins (GitHub Pages에서 지원하는 기본 플러그인 사용)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO 및 피드 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 빌드 설정
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
